[package]
name = "spacekernel"
description = "Space OS microkernel (x86_64-unknown-none)"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "spacekernel"
test = false
bench = false

[dependencies]
spaceabi.workspace = true
x86_64.workspace = true
linked_list_allocator.workspace = true
noto-sans-mono-bitmap.workspace = true
