[package]
name = "ipc_echo"
description = "Test: IPC echo server with handle transfer"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "ipc_echo"
test = false
bench = false

[dependencies]
spaceabi.workspace = true
libspace.workspace = true
